### ISSUE TITLE
Add this project to lightline

### ISSUE THREAD

**Issue by fabienengels** [shinchu/lightline-gruvbox.vim#2]
Hi,

Won't be possible to add your work directly to the lightline project ?

Thank you in advance

**Comment by E1k3** [comment]
This theme is already included with the gruvbox colorscheme for vim.
So, if you use gruvbox for vim already, just add `let g:lightline = {}
let g:lightline.colorscheme = 'gruvbox'` to your vimrc without adding this plugin.

For this reason, I would suggest you ask the gruvbox creator/maintainer at https://github.com/morhetz/gruvbox to add his lightline theme to the lightline project.

**Comment by shinchu** [comment]
@fabienengels Thanks for the suggestion! As @E1k3 commented, I'd also suggest you ask the gruvbox colorscheme maintainer to add his theme to the lightline project.
