### ISSUE TITLE
Add note that there is a lightline theme included with `gruvbox-community / gruvbox`

### ISSUE THREAD

**Issue by shea-parkes** [shinchu/lightline-gruvbox.vim#8]
At some point in the last few years, the `gruvbox-community` maintainers added a lightline theme to the main gruvbox repo:

https://github.com/gruvbox-community/gruvbox/blob/50e0a8227826418b9e94281ef3abaffd82041f24/autoload/lightline/colorscheme/gruvbox.vim

They made subtly different color choices than this solution, but it can be nice to not manage additional plugin installs.

I greatly appreciate this solution being available for as long as it has been.  Thanks!

**Comment by shinchu** [comment]
Hi @shea-parkes, thank you very much for your comment!
I added a note on that in README.
